@startuml
left to right direction
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontSize 14
hide circle

title MED-06 - ERD: ACCESSIBILITY

entity events {
  * id : UUID <<PK>>
}

entity event_accessibility {
  * event_id : UUID <<PK, FK>>
  * accessibility_feature_id : UUID <<PK, FK>>
}

entity accessibility_features {
  * id : UUID <<PK>>
  --
  name : VARCHAR(120) <<UQ>>
  description : TEXT
}

events ||--o{ event_accessibility
accessibility_features ||--o{ event_accessibility

@enduml
